---
- hosts: all
  become: yes
  tasks: 
    - name: Create a new file
      file:
        path: /tmp/newfolder
        state: directory
      register: abc
    - debug:
        msg: "{{ abc.stdout_lines }}"

